# Generated by Django 4.0.4 on 2022-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
