# Generated by Django 4.0 on 2022-04-14 17:16

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='first_name',
            field=core.models.LowerCase(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='last_name',
            field=core.models.LowerCase(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
    ]
