# Generated by Django 4.0 on 2022-04-30 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_custom_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
