# Generated by Django 4.1.1 on 2022-09-22 05:16

import clients.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', clients.models.LowerCase(max_length=100, unique=True)),
                ('client_group', clients.models.LowerCase(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], default='a', max_length=10)),
                ('business_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address_1', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line1')),
                ('address_2', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line2')),
                ('address_3', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line3')),
                ('address_4', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line4')),
                ('city', clients.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='city')),
                ('state', clients.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='state')),
                ('zipcode', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='zipcode')),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('client_des', models.CharField(blank=True, max_length=150, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', clients.models.LowerCase(blank=True, default='india', max_length=100, null=True)),
                ('state_name', clients.models.LowerCase(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_name', clients.models.LowerCase(max_length=100)),
                ('transport_code', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', clients.models.LowerCase(blank=True, max_length=100, null=True, verbose_name='station')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.state')),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', clients.models.LowerCase(error_messages={'unique': 'A consignee already exists.'}, max_length=150)),
                ('state', clients.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='state')),
                ('station', clients.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='station')),
                ('transport', clients.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='transport')),
                ('private_marka', models.CharField(blank=True, max_length=100, null=True)),
                ('is_client', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_varified', models.DateTimeField(auto_now_add=True, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
