# Generated by Django 4.0 on 2022-04-02 09:16

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='consignee_name',
            field=clients.models.LowerCase(error_messages={'unique': 'A consignee already exists.'}, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=clients.models.LowerCase(blank=True, max_length=100, null=True, verbose_name='station'),
        ),
    ]
