# Generated by Django 4.0.4 on 2022-06-03 16:30

import clients.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_consignee_state_alter_consignee_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=clients.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=clients.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='state',
            field=clients.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='station',
            field=clients.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='transport',
            field=clients.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='transport'),
        ),
    ]
