# Generated by Django 4.0.4 on 2022-07-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_consignee_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to='clients.client'),
        ),
    ]
