# Generated by Django 4.0.4 on 2022-08-19 17:57

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', items.models.LowerCase(max_length=100, unique=True)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='item')),
                ('hsn_sac', items.models.LowerCase(blank=True, max_length=50, null=True)),
                ('comment', items.models.LowerCase(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', items.models.LowerCase(max_length=100, unique=True)),
                ('group_des', items.models.LowerCase(max_length=200)),
                ('comment', items.models.LowerCase(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', items.models.LowerCase(max_length=100, unique=True)),
                ('short_unit_name', items.models.LowerCase(max_length=10, unique=True)),
                ('comment', items.models.LowerCase(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', items.models.LowerCase(max_length=100)),
                ('item_variant_img', models.ImageField(blank=True, null=True, upload_to='itemvariant')),
                ('con_factor', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, null=True)),
                ('client_price_a', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, null=True)),
                ('client_price_b', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, null=True)),
                ('client_price_c', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, null=True)),
                ('client_price_d', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, null=True)),
                ('comment', items.models.LowerCase(blank=True, max_length=200, null=True)),
                ('alternate_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.unit')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item_group'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.unit'),
        ),
    ]
