# Generated by Django 4.1.1 on 2022-09-26 15:06

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='packing_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_unit_name', items.models.LowerCase(max_length=30)),
                ('packing_unit_des', items.models.LowerCase(max_length=200)),
                ('packing_unit_comment', items.models.LowerCase(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', items.models.LowerCase(max_length=30)),
                ('unit_des', items.models.LowerCase(max_length=100)),
                ('unit_comment', items.models.LowerCase(max_length=200)),
            ],
        ),
    ]
