# Generated by Django 4.0.4 on 2022-09-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_variant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, null=True),
        ),
    ]
