# Generated by Django 4.1.1 on 2022-10-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='items.unit'),
        ),
    ]
