# Generated by Django 4.0.4 on 2022-07-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_unit_short_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_variant',
            name='alternate_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.unit'),
        ),
    ]
