# Generated by Django 4.1.1 on 2022-09-26 17:45

from django.db import migrations
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_packing_unit_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing_unit',
            name='packing_unit_abbreviation',
            field=items.models.LowerCase(default='cr', max_length=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_abbreviation',
            field=items.models.LowerCase(default='kg', max_length=10),
        ),
    ]
