# Generated by Django 4.1.1 on 2022-10-05 09:02

from django.db import migrations
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_abbreviation',
            field=items.models.LowerCase(max_length=10),
        ),
    ]
