# Generated by Django 4.0.4 on 2022-06-02 14:29

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('des', orders.models.LowerCase(blank=True, max_length=200, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('consignee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.consignee')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', orders.models.LowerCase(max_length=200)),
                ('item_variant_name', orders.models.LowerCase(max_length=200)),
                ('item_price', models.DecimalField(decimal_places=2, default=1.1, max_digits=7)),
                ('item_qty', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('comment', orders.models.LowerCase(blank=True, max_length=200, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('consignee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.consignee')),
                ('item_Variant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item_variant')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.consignee_order')),
                ('order_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_unit', to='items.unit')),
                ('price_per_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='per_unit', to='items.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Order_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_qty', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('status', orders.models.LowerCase(blank=True, choices=[('cancelled', 'cancelled'), ('dispatched', 'dispatched'), ('transferred', 'transferred')], default='dispatched', max_length=30, null=True)),
                ('comment', orders.models.LowerCase(blank=True, max_length=200, null=True)),
                ('item_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item_order')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Order_Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_qty', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('comment', orders.models.LowerCase(blank=True, max_length=200, null=True)),
                ('item_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item_order')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item_order_status')),
            ],
        ),
    ]
