# Generated by Django 4.0.4 on 2022-06-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_order',
            old_name='item_Variant_id',
            new_name='item_variant_id',
        ),
        migrations.RemoveField(
            model_name='item_order',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='item_order',
            name='item_variant_name',
        ),
    ]
