# Generated by Django 4.0.4 on 2022-06-07 13:35

from django.db import migrations
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignee_order',
            old_name='des',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='consignee_order',
            name='order_type',
            field=orders.models.LowerCase(blank=True, choices=[('sales', 'sales'), ('purchase', 'purchase')], default='sales', max_length=30, null=True),
        ),
    ]
