# Generated by Django 4.0.4 on 2022-06-09 03:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_city_alter_client_state_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignee_order',
            old_name='des',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='item_order',
            old_name='item_price',
            new_name='item_veriant_price',
        ),
        migrations.AddField(
            model_name='consignee_order',
            name='order_type',
            field=orders.models.LowerCase(blank=True, choices=[('sales', 'sales'), ('purchase', 'purchase')], default='sales', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item_order_status',
            name='docket_number',
            field=orders.models.LowerCase(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item_order_transfer',
            name='client_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_order_transfer',
            name='consignee_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='clients.consignee'),
            preserve_default=False,
        ),
    ]
