# Generated by Django 4.0.4 on 2022-09-03 15:45

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_order_status',
            name='private_marka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item_order_status',
            name='state',
            field=orders.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='item_order_status',
            name='station',
            field=orders.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='station'),
        ),
        migrations.AddField(
            model_name='item_order_status',
            name='transport',
            field=orders.models.LowerCase(blank=True, max_length=64, null=True, verbose_name='transport'),
        ),
    ]
