# Generated by Django 4.1.1 on 2022-10-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_order',
            name='packing_type',
        ),
        migrations.RemoveField(
            model_name='item_order',
            name='price_per_unit',
        ),
        migrations.AddField(
            model_name='item_order',
            name='item_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.unit'),
        ),
        migrations.AddField(
            model_name='item_order',
            name='packing_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.packing_unit'),
        ),
    ]
