# Generated by Django 4.0.4 on 2022-07-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_item_variant_id_item_order_item_variant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_order',
            name='item_qty',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
    ]
