# Generated by Django 4.1.1 on 2022-10-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_item_unit'),
        ('orders', '0002_remove_item_order_packing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_order',
            name='item_unit',
        ),
        migrations.AlterField(
            model_name='item_order',
            name='packing_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='items.packing_unit'),
        ),
    ]
