# Generated by Django 4.1.1 on 2022-10-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_item_unit'),
        ('orders', '0003_remove_item_order_item_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_order',
            name='packing_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.packing_unit'),
        ),
    ]
