# Generated by Django 4.0.4 on 2022-07-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_item_order_item_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_order_transfer',
            name='item_qty',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
    ]
