# Generated by Django 4.0.4 on 2022-07-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_unit_short_unit_name'),
        ('orders', '0005_alter_item_order_item_veriant_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_order_status',
            name='order_id',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='orders.consignee_order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_order_transfer',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='items.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_order_transfer',
            name='item_variant_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='items.item_variant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_order_transfer',
            name='item_veriant_price',
            field=models.DecimalField(decimal_places=1, default=1.1, max_digits=7),
        ),
        migrations.AddField(
            model_name='item_order_transfer',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.consignee_order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_order_transfer',
            name='order_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Item_Order_Transfer_order_unit', to='items.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_order_transfer',
            name='price_per_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Item_Order_Transfer_per_unit', to='items.unit'),
            preserve_default=False,
        ),
    ]
