# Generated by Django 4.1.1 on 2022-10-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_item_order_item_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_order',
            name='item_unit',
        ),
    ]
