# Generated by Django 4.0.4 on 2022-07-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_item_order_status_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_order',
            name='item_veriant_price',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='item_order_transfer',
            name='item_veriant_price',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=7),
        ),
    ]
