# Generated by Django 4.1.1 on 2022-10-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_unit_unit_abbreviation'),
        ('orders', '0006_remove_item_order_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_order',
            name='item_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='items.unit'),
            preserve_default=False,
        ),
    ]
