# Generated by Django 4.0.4 on 2022-07-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_consignee_client_id'),
        ('orders', '0009_remove_item_order_status_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_order_status',
            name='client_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_order_status',
            name='consignee_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='clients.consignee'),
            preserve_default=False,
        ),
    ]
