# Generated by Django 4.0.4 on 2022-08-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_item_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_order',
            old_name='order_unit',
            new_name='order_unit_id',
        ),
        migrations.RenameField(
            model_name='item_order',
            old_name='price_per_unit',
            new_name='price_per_unit_id',
        ),
    ]
