# Generated by Django 4.0.4 on 2022-08-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_consignee_client_id'),
        ('orders', '0015_item_order_status_transfer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_order_status',
            name='consignee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignee_id', to='clients.consignee'),
        ),
    ]
